# Generated by Django 4.2.3 on 2023-08-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rr',
            fields=[
                ('per_id', models.IntegerField(primary_key=True, serialize=False)),
                ('per_name', models.CharField(max_length=100)),
            ],
        ),
    ]
